In [16]:
import numpy as np
import torch.nn as nn
import torch
import math
import matplotlib.pyplot as plt
import cv2
import csv
import tensorflow as tf
import torchvision
import torchvision.transforms as transforms
import torch.nn.functional as F
import sys

In [ ]:
img_path = 'test_image\L.jpeg'

test_img = cv2.imread(img_path, cv2.IMREAD_COLOR)

cv2.imshow('loaded image', test_img)

cv2.waitKey(0)

cv2.destroyAllWindows()

In [29]:
print(test_img.shape)
print(test_img.dtype)
print(test_img.data)
print(test_img.astype)

(400, 400, 3)
uint8
<built-in method astype of numpy.ndarray object at 0x000001EC4D48D530>


In [ ]:
print(test_img[:1])

test_img_tensor = torch.tensor(test_img)
print(test_img_tensor[:1])

test_img_tensor = test_img_tensor / 255
print(test_img_tensor[:1])

to_tensor = transforms.ToTensor()
test_img_tensor2 = to_tensor(test_img)
print(test_img_tensor2.T[:1])
print(test_img_tensor2.permute(1,2,0)[:1])


[[[ 77 105 112]
  [ 80 108 115]
  [ 86 112 118]
  ...
  [ 25  24  26]
  [ 26  25  27]
  [ 27  26  28]]]
tensor([[[ 77, 105, 112],
         [ 80, 108, 115],
         [ 86, 112, 118],
         ...,
         [ 25,  24,  26],
         [ 26,  25,  27],
         [ 27,  26,  28]]], dtype=torch.uint8)
tensor([[[0.3020, 0.4118, 0.4392],
         [0.3137, 0.4235, 0.4510],
         [0.3373, 0.4392, 0.4627],
         ...,
         [0.0980, 0.0941, 0.1020],
         [0.1020, 0.0980, 0.1059],
         [0.1059, 0.1020, 0.1098]]])
tensor([[[0.3020, 0.4118, 0.4392],
         [0.3216, 0.4314, 0.4588],
         [0.3451, 0.4549, 0.4824],
         ...,
         [0.6667, 0.7686, 0.8235],
         [0.6627, 0.7686, 0.8235],
         [0.6627, 0.7686, 0.8235]]])
tensor([[[0.3020, 0.4118, 0.4392],
         [0.3137, 0.4235, 0.4510],
         [0.3373, 0.4392, 0.4627],
         ...,
         [0.0980, 0.0941, 0.1020],
         [0.1020, 0.0980, 0.1059],
         [0.1059, 0.1020, 0.1098]]])


In [78]:
def transform(img): #ndarray (h, w, c) -> tensor (c/255, h/255, w/255)
    """
    
    img = torch.tensor(img)
    img = img.permute(2,0,1)
    img = img/255
    
    """
    img = transforms.ToTensor()(img)
    img = (img - 0.5) / 0.5 # transforms.Noramilze((0.5,0.5,0.5), (0.5))
    
    return img

test_img_transform = transform(test_img)

test_img_transform.dtype

torch.float32

1. 이미지를 cv2.imread(path, cv2.imread_color) 등을 통해 읽으면 nd.array 형태로 저장됨.
2. ToTensor는 PIL 또는 ndarray를 C * H * W 형태로 치환하고 255로 나눠 정규화해줌.
3. pytorch에서 blabla.T 처럼 전치하는 것은 위험함. .T는 마지막 두차원만 전치시켜줌.
    예를 들어 (C, H, W) 형태의 텐서를 .T하면 (C, W, H)가 됨. 즉 원하는 차원변경이 아닐 수 있다.
    따라서, .permute(*dims) 함수를 사용해 전치시키는 습관이 필요하다.


In [79]:
download_path = 'test_image'

trainset= torchvision.datasets.CIFAR10(root=download_path, train=True,
                                      download=True, transform = transform)

testset= torchvision.datasets.CIFAR10(root=download_path, train=False,
                                      download=True, transform = transform)


In [87]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('airplane', 'automobile', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

In [89]:
print(trainset[0][0].shape)

torch.Size([3, 32, 32])
